image: node:14.19.0

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH

cache:
  key:
    files:
      - package-lock.json
  paths:
    - .npm/

before_script:
  - npm ci --cache .npm --prefer-offline

tests:
  stage: test
  script:
    - echo 'Test started.'
    - npm run test
    - echo 'Test finished.'

pages:
  stage: deploy
  script:
    - echo 'Deploy started.'
    - npm run parse
    - echo 'Deploy finished.'
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == "release"
