name: GitHub Page

on:
  push:
    branches:
      - release

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    name: Build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Start
        run: echo "→ Started"
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: release
          fetch-depth: 1
      - name: Prepare
        uses: actions/setup-node@v3
        with:
          node-version: 14.19
          cache: "npm"
      - name: Install
        run: npm ci
      - name: Build
        run: npm run parse
      - name: Upload
        uses: actions/upload-pages-artifact@v1
        if: ${{ github.ref_name == "release" }}
        with:
          path: public
      - name: Deploy
        id: deployment
        if: ${{ github.ref_name == "release" }}
        uses: actions/deploy-pages@v1
      - name: Completed
        run: echo "→ Completed"
